#!/bin/bash
shopt -s nocasematch
export PS1="\[$(tput setaf 7)\]\u@\h:\W $ \[$(tput sgr0)\]"
alias vi='vim'
alias ll='ls -l'
alias la='ls -al'
alias du='du -BM --max-depth=1'
alias ssh='ssh -Y'
umask 022

export system=$(uname -s)
export arch=$(uname -m | tr ' ' '-')

#color scheme for "ls" command
if [ "$system" = "Linux" ]; then
  [ -e "$HOME/.dircolors" ] && DIR_COLORS="$HOME/.dircolors"
  [ -e "$DIR_COLORS" ] || DIR_COLORS=""
  eval "`dircolors -b $DIR_COLORS`"
  export nproc=`nproc`
elif [ "$system" = "Darwin" ]; then
  export CLICOLOR=1
  export LSCOLORS=dxfxcxdxbxegedabagacad
  alias ls="ls -G"
  export nproc=`sysctl -n hw.ncpu`
fi

#echo "hostname [$HOSTNAME] platform[$MACHTYPE]"
if [[ $HOSTNAME =~ ^plpa|cfans|^MacBook ]]; then
  export git=$home/git
elif [[ $HOSTNAME =~ ^login|^tern|^noddy|^kh ]]; then
  export git=$home/git
elif [[ $HOSTNAME =~ ^^mirror|^lab.*[0-9]+|^node|^ln|^cn ]]; then
  export soft_msi=/soft
  for subpath in blat/34 muscle/3.8.31 \
    exonerate/2.2.0 structure/2.3.3
  do
    if [[ -d $soft_msi/$subpath/bin ]]; then
      export PATH=$soft_msi/$subpath/bin:$PATH
    fi
  done
else
  echo 'unknown host -> check your bash_profile'
fi

# Add software paths
prefix=$HOME/$arch
export PATH=$PATH:$prefix/bin
#export LD_LIBRARY_PATH=$prefix/lib:$LD_LIBRARY_PATH
export soft=$prefix/soft
if [[ -d $soft ]]; then
  for subpath in zlib gcc boost libsequence \
    samtools bamtools bedtools vcftools bedops \
    hdf tabix bowtie2 sra blast bwtool\
    clustalw clustalo paml4.8 \
    parallel blast CAP3 cmake cufflinks mcl \
    augustus maker ocaml opam \
    emboss gd geco genometools gmap hmmer mysql orthomcl \
    R root tophat trimAl wise2 GEM kent unafold imagemagick
  do
    if [[ -d $soft/$subpath/bin ]]; then
      export PATH=$soft/$subpath/bin:$PATH
    fi
    if [[ -d $soft/$subpath/bin64 ]]; then
      export PATH=$soft/$subpath/bin64:$PATH
    fi
    if [[ -d $soft/$subpath/lib ]]; then
      export LD_LIBRARY_PATH=$soft/$subpath/lib:$LD_LIBRARY_PATH
    fi
    if [[ -d $soft/$subpath/lib64 ]]; then
      export LD_LIBRARY_PATH=$soft/$subpath/lib64:$LD_LIBRARY_PATH
    fi
  done
  for subpath in RepeatMasker interproscan mummer \
    bwa lastz snap trimal phyml paramugsy blasr pal2nal
  do
    export PATH=$soft/$subpath:$PATH
  done
  for subpath in augustus
  do
    export PATH=$soft/$subpath/scripts:$PATH
  done
  
fi

# generic locations
export home=$HOME
export src=$home/Source
export data=$home/Data
export genome=$home/Data/genome
export misc1=$home/Data/misc1
export misc2=$home/Data/misc2
export misc3=$home/Data/misc3
export misc4=$home/Data/misc4
export dbox=$home/Dropbox
export git=$home/git

# repositories
export luffy=$git/luffy
export code=$luffy
export conf=$luffy/sysconf
export robin=$git/robin
export spada=$git/spada
export rosar=$git/rgeneclust
export urt=$git/soyurt
export PATH=$rosar:$spada:$PATH

# Perl
export PERL_HOME=$prefix/soft/perl
#export PERL_MM_OPT="INSTALL_BASE=$PERL_HOME"
#export PERL_MB_OPT="--install_base $PERL_HOME"
export CPANLIB=$PERL_HOME/lib/perl5:$PERL_HOME/lib64/perl5
export PERL5LIB=$PERL_HOME/lib/perl5:$PERL_HOME/lib64/perl5
export SCRIPT_HOME_PERL=$code/perl
export PATH=$SCRIPT_HOME_PERL:$PERL_HOME/bin:$PATH

# Python
export PYTHON_HOME=$prefix/soft/python
export PYTHONUSERBASE=$prefix/soft/python
export PYTHONPATH=${PYTHON_HOME}/lib/python2.7/site-packages
#export LD_LIBRARY_PATH=${PYTHON_HOME}/lib:$LD_LIBRARY_PATH
export SCRIPT_HOME_PYTHON=$robin
export PATH=$SCRIPT_HOME_PYTHON:$PYTHON_HOME/bin:$PATH

# C++
export PATH=$code/c++/bin:$PATH

# R
export SCRIPT_HOME_R=$code/r

# SVN
export SVN_EDITOR=vi

# LATEX
export PATH=$prefix/soft/tex/bin/x86_64-linux:$PATH

# ROOT
export ROOTSYS=$prefix/soft/root

# Augustus
export AUGUSTUS_CONFIG_PATH=$soft/augustus/config

# Kent Source and Bio::BigFile
export KENT_SRC=$git/kent/src

# Maker
export ZOE=$soft/snap

# Mugsy
export MUGSY_INSTALL=$soft/mugsy

# OPAM configuration
. /home/youngn/zhoup/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

# misc
unset prefix

