#!/bin/bash
shopt -s nocasematch
export PS1="\[$(tput setaf 7)\]\u@\h:\W $ \[$(tput sgr0)\]"
alias vi='vim'
alias ll='ls -l'
alias la='ls -al'
alias du='du -BM --max-depth=1'
alias qu='watch qstat -u zhoux379'
alias gm='git commit -a -m "normal commit"; git push origin master'
alias sm='ssh -t login ssh ms'
alias snk='snakemake -j 8 --cluster-config cluster.yaml --cluster "qsub -q {cluster.q} -l {cluster.l} -N {cluster.N} -M {cluster.M} -m {cluster.m} -r {cluster.r}"'
#alias ssh='ssh -Y'
umask 022

export system=$(uname -s)
export arch=$(uname -m | tr ' ' '-')

#color scheme for "ls" command
if [ "$system" = "Linux" ]; then
    [ -e "$HOME/.dircolors" ] && DIR_COLORS="$HOME/.dircolors"
    [ -e "$DIR_COLORS" ] || DIR_COLORS=""
    eval "`dircolors -b $DIR_COLORS`"
    export nproc=`nproc`
elif [ "$system" = "Darwin" ]; then
    export CLICOLOR=1
    export LSCOLORS=dxfxcxdxbxegedabagacad
    alias ls="ls -G"
    export nproc=`sysctl -n hw.ncpu`
fi

#echo "hostname [$HOSTNAME] platform[$MACHTYPE]"
if [[ $HOSTNAME =~ ^plpa|cfans|^MacBook ]]; then
    export git=$home/git
elif [[ $HOSTNAME =~ ^login|^tern|^noddy|^kh ]]; then
    export git=$home/git
elif [[ $HOSTNAME =~ ^^mirror|^lab.*[0-9]+|^node|^ln|^cn ]]; then
    export soft_msi=/soft
    module load java
else
    echo 'unknown host -> check your bash_profile'
fi

# Add software paths
export soft=$HOME/software
if [[ -d $soft ]]; then
    for subpath in miniconda3 vim kent \
#    npm root GEM unafold 
    do
        if [[ -d $soft/$subpath/bin ]]; then
            export PATH=$soft/$subpath/bin:$PATH
        fi
        if [[ -d $soft/$subpath/bin64 ]]; then
            export PATH=$soft/$subpath/bin64:$PATH
        fi
        if [[ -d $soft/$subpath/lib ]]; then
            export LD_LIBRARY_PATH=$soft/$subpath/lib:$LD_LIBRARY_PATH
        fi
        if [[ -d $soft/$subpath/lib64 ]]; then
            export LD_LIBRARY_PATH=$soft/$subpath/lib64:$LD_LIBRARY_PATH
        fi
    done
    for subpath in RepeatMasker interproscan \
        paramugsy gatk
    do
        if [ -d $soft/$subpath ] || [ -h $soft/$subpath ]; then
            export PATH=$soft/$subpath:$PATH
        fi
    done
    for subpath in miniconda3
    do
        #export CFLAGS="-I$soft/$subpath/include $CFLAGS"
        export LDFLAGS="-L$soft/$subpath/lib $LDFLAGS"
    done
fi

# generic locations
export home=$HOME
export src=$home/source
export git=$home/git
export proj=$home/projects
export data=$home/data
export genome=$home/data/genome
export misc1=$data/misc1
export misc2=$data/misc2
export misc3=$data/misc3
export misc4=$data/misc4
export PATH=$HOME/bin:$PATH

# repositories
export maize=$git/maize
export luffy=$git/luffy
export code=$maize
export conf=$luffy/sysconf
export urt=$git/soyurt
export ped=$git/pedtools
export site=$git/maizeumn.github.io
export PATH=$code:$rosar:$spada:$ped:$PATH

export PATH=$luffy/c++/bin:$luffy/bash:$PATH
export PATH=$soft/ruby/bin:$PATH
export SCRIPT_HOME_R=$luffy/r

# Python
export PYTHONPATH=$git:$PYTHONPATH

# projects
export briggs=$proj/briggs
export biomap=$proj/biomap
export poly=$proj/polyTE
export dys=$proj/dysgenic
export set=$proj/settles
export rs=$proj/3rnaseq
for pname in briggs biomap polyTE dysgenic settles
do
    if [ -d $proj/$pname/src ] || [ -h $proj/$pname/src ]; then
        export PATH=$proj/$pname/src:$PATH
	fi
done
 
# Perl
#export PERL_HOME=$soft/perl
#export PERL_MM_OPT="INSTALL_BASE=$PERL_HOME"
#export PERL_MB_OPT="--install_base $PERL_HOME"
#export CPANLIB=$PERL_HOME/lib/perl5:$PERL_HOME/lib64/perl5
#export PERL5LIB=$soft/vcftools/share/perl5:$PERL_HOME/lib/perl5:$PERL_HOME/lib64/perl5
#export PATH=$luffy/perl:$PERL_HOME/bin:$PATH

# SVN
export SVN_EDITOR=vi

# LATEX
export PATH=$soft/tex/2016/bin/x86_64-linux:$PATH

# Augustus
export AUGUSTUS_CONFIG_PATH=$soft/augustus/config

# Trinity
export TRINITY_HOME=$soft/trinity
