DIR_Home  <- Sys.getenv("WORK")
DIR_Data  <- file.path(DIR_Home, "Data" )
DIR_In  <- file.path(DIR_Data, "in" )
DIR_Out  <- file.path(DIR_Data, "out" )
DIR_Genome  <- file.path(DIR_Data, "genome" )
DIR_RData  <- file.path(DIR_Out, "RData" )
DIR_Misc1 <- file.path(DIR_Data, "misc1")
DIR_Misc2 <- file.path(DIR_Data, "misc2")
DIR_Misc3 <- file.path(DIR_Data, "misc3")
DIR_Stat  <- file.path(DIR_Data, "stat" )
DIR_Repo  <- file.path(DIR_Data, "repo" )
DIR_Circos <- file.path(DIR_Misc1, "circos")
DIR_R <- file.path(DIR_Misc1, "r")

#source("http://www.bioconductor.org/biocLite.R")
require(ggplot2)
require(data.table)
#require(Hmisc)
#require(ape)
#require(gplots)
#require(VennDiagram)

#bioconductor packages
#require(ctc)
#require(limma)
#require(Heatplus)
#require(Rsamtools)
#require(GenomicRanges)
#require(GenomicFeatures)

source('function.R')
